// @generated by protobuf-ts 2.9.5
// @generated from protobuf file "kri.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ProyekPb
 */
export interface ProyekPb {
    /**
     * @generated from protobuf field: repeated SequenceDiagramPb koleksiSequenceDiagram = 1;
     */
    koleksiSequenceDiagram: SequenceDiagramPb[];
}
/**
 * @generated from protobuf message SequenceDiagramPb
 */
export interface SequenceDiagramPb {
    /**
     * @generated from protobuf field: string nama = 1;
     */
    nama: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ProyekPb$Type extends MessageType<ProyekPb> {
    constructor() {
        super("ProyekPb", [
            { no: 1, name: "koleksiSequenceDiagram", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => SequenceDiagramPb }
        ]);
    }
    create(value?: PartialMessage<ProyekPb>): ProyekPb {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.koleksiSequenceDiagram = [];
        if (value !== undefined)
            reflectionMergePartial<ProyekPb>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ProyekPb): ProyekPb {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated SequenceDiagramPb koleksiSequenceDiagram */ 1:
                    message.koleksiSequenceDiagram.push(SequenceDiagramPb.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ProyekPb, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated SequenceDiagramPb koleksiSequenceDiagram = 1; */
        for (let i = 0; i < message.koleksiSequenceDiagram.length; i++)
            SequenceDiagramPb.internalBinaryWrite(message.koleksiSequenceDiagram[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ProyekPb
 */
export const ProyekPb = new ProyekPb$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SequenceDiagramPb$Type extends MessageType<SequenceDiagramPb> {
    constructor() {
        super("SequenceDiagramPb", [
            { no: 1, name: "nama", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SequenceDiagramPb>): SequenceDiagramPb {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.nama = "";
        if (value !== undefined)
            reflectionMergePartial<SequenceDiagramPb>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SequenceDiagramPb): SequenceDiagramPb {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string nama */ 1:
                    message.nama = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SequenceDiagramPb, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string nama = 1; */
        if (message.nama !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.nama);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message SequenceDiagramPb
 */
export const SequenceDiagramPb = new SequenceDiagramPb$Type();
